name: daily_diary
description: A diary that starts with a blank page every day (while saving the previous ones)
publish_to: 'none'

version: 1.4.5+17

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # Core plugins so Flutter generates .dart_tool/flutter/build_plugins
  shared_preferences: ^2.3.3
  path_provider: ^2.1.5
  url_launcher: ^6.3.2

  # Internationalization
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # UI/UX
  cupertino_icons: ^1.0.8
  flex_color_picker: ^3.7.0

  # File handling
  file_picker: ^8.1.7
  archive: ^4.0.2

  # Desktop (keep if you target desktop)
  flutter_window_close: ^1.2.0

  # Other
  toml: ^0.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Stay on 5.x because 6.x requires Dart >= 3.8
  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true
