name: daily_diary
description: A diary that starts with a blank page every day (while saving the previous ones)
publish_to: 'none'

version: 1.4.5+17

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # --- Core plugins (these ensure .dart_tool/flutter/build_plugins is created) ---
  shared_preferences: ^2.3.3     # for saving small pieces of data (settings, folder URIs, etc.)
  path_provider: ^2.1.5          # access to app/documents/cache directories
  url_launcher: ^6.3.2           # open links in browser, dialer, etc.

  # --- Internationalization ---
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # --- UI/UX ---
  cupertino_icons: ^1.0.8
  flex_color_picker: ^3.7.1      # bumped to latest minor release

  # --- File handling ---
  file_picker: ^10.3.3           # bumped to latest stable (8.x is older)
  archive: ^4.0.7                # bumped to latest 4.x

  # --- Desktop-specific (safe to keep if you target desktop) ---
  flutter_window_close: ^1.3.0   # bumped to latest

  # --- Other ---
  toml: ^0.16.0                  # configuration parsing (still stable)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0          # update to latest lint set

flutter:
  generate: true
  uses-material-design: true
