name: daily_diary
description: A diary that starts with a blank page every day (while saving the previous ones)
publish_to: 'none'

version: 1.4.5+17

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # SAF-based storage + prefs for persisted URI
  saf: ^2.1.2
  shared_preferences: ^2.2.3

  flutter_localizations:
    sdk: flutter
  intl: any

  cupertino_icons: ^1.0.8
  path_provider: ^2.0.11
  toml: ^0.16.0
  file_picker: ^8.1.7
  flutter_window_close: ^1.0.0
  archive: ^4.0.2
  flex_color_picker: ^3.3.0
  url_launcher: ^6.2.1

  # Remove this unless you truly need it elsewhere in the codebase.
  # shared_storage:
  #   git:
  #     url: https://github.com/AlexBacich/shared-storage
  #     ref: 8784c39b909324df8913dd30fa416b8a50d55f49

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true
