name: Android CI (SAF)

on:
  workflow_dispatch:
  push:
    branches: [ main, feat/saf-storage ]
    paths:
      - "lib/**"
      - "android/**"
      - "pubspec.yaml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter --version
      - run: flutter pub get
      - run: flutter build apk --release
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
