name: Android Release (Flutter)

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
    paths:
      - "**/*.dart"
      - "pubspec.yaml"
      - "android/**"
      - ".github/workflows/android-release.yml"

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter (stable)
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"      # <-- correct usage
          cache: true

      - name: Show Flutter version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Generate localizations (optional but explicit)
        run: flutter gen-l10n

      - name: Build APK (release)
        run: flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
